/* 1001+ 浮世绘 — 界面文案（中英双语）
   作品数据（含双语字段）已内联在 data.js，此处仅保留 UI 文案。
*/
window.LANG = {
ui: {
  zh: {
    title_sub:" 浮世绘", subtitle:"江户 · 明治 · 木版画的三百年",
    works:"幅版画", eras:"个时代", artists:"位艺术家",
    all_eras:"全部时代", all_media:"全部媒材", all_regions:"全部地区",
    random:"随机作品", all:"全部",
    timeline:"时间线", timeline_off:"退出时间线",
    bce:"史前与古代", ancient:"1–14 世纪",
    m_date:"年代", m_medium:"媒材", m_location:"馆藏地", m_country:"国家/地区",
    prev:"← 上一件", next:"下一件 →", of_total:"件",
    zoom_hint:"滚轮缩放 · 双击放大 · 拖动平移 · 双指缩放",
    view_original:"查看原图", download:"下载", close:"关闭",
    no_results:"未找到符合条件的作品", reset:"重置筛选",
    img_na:"尚未取得可公开展示的图片", view_wiki:"在 Wikipedia 查看",
    // 「暂无」会让人以为是数据缺口、以后会补；对仍在版权期的作品要讲清是法律原因与解禁年份
    cr_note:"本作仍在版权保护期，没有自由授权的图像。多数地区预计 {y} 年进入公有领域。",
    cr_note_unk:"本作仍在版权保护期，没有自由授权的图像。",
    fav:"收藏", fav_on:"已收藏", fav_only:"仅看收藏", fav_empty:"还没有收藏任何作品，点卡片上的 ♡ 即可收藏",
    by_artist:"按艺术家", all_artists:"全部艺术家", artist_works:"幅版画",
    by_museum:"按馆藏", filter_artist:"筛选艺术家…", filter_museum:"筛选博物馆…",
    sort_by_count:"⇅ 按数量", sort_by_name:"⇅ 按名称",
    related_by:"同一艺术家的其他作品",
    related_era:"同时代的其他作品",
    museums:"个博物馆",
    clear:"清除", zoom_in:"放大", zoom_out:"缩小", reset_zoom:"重置", view_grid:"切换视图", to_top:"回到顶部",
    dlg_art:"艺术品详情", dlg_lightbox:"高清大图", dlg_help:"键盘快捷键",
    more_by:"查看该艺术家全部作品 →", share:"复制链接", shared:"链接已复制 ✓",
    exhibit:"藏品展", back_all:"‹ 返回全部作品",
    daily:"每日一作", search_ph2:"搜索 名称 / 艺术家 / 拼音 / 年代…",
    sort_label:"排序", sort_default:"默认（名气）", sort_year_asc:"年代：早→晚", sort_year_desc:"年代：晚→早", sort_title:"按标题",
    kbd:"快捷键", kbd_search:"聚焦搜索框", kbd_random:"随机作品", kbd_artist:"切换艺术家视图", kbd_timeline:"切换时间线", kbd_fav:"切换仅看收藏", kbd_nav:"上一件 / 下一件", kbd_close:"关闭弹窗 / 帮助", kbd_help:"显示本帮助",
    about:"关于", about_title:"关于本站",
    about_intro:"「1001+ 浮世绘」收录日本木版画三百年——葛饰北斋、歌川广重、喜多川歌麿、歌川国芳、月冈芳年、铃木春信。图片与著录来自大都会、克利夫兰、明尼阿波利斯三馆开放数据与维基共享资源。与姊妹站分工：绘画、写本与造像在「1001+ 人类艺术瑰宝」，工艺器物在「1001+ 人类器物」。",
    about_sources:"作品信息采集自 Wikidata 结构化数据（按维基百科收录度排序），图片来自 Wikimedia Commons 公有领域资源，并已下载缓存于本站。",
    about_tech:"纯静态前端，无框架、无运行时依赖；支持中英双语、拼音搜索、离线访问（PWA），部署于 GitHub Pages。",
    about_credits:"图片版权归原作者及收藏机构所有；少数 20 世纪受版权保护的作品以占位卡呈现，并提供 Wikipedia 链接。",
    about_works:"幅版画", about_artists:"位艺术家", about_images:"张本地高清图",
    about_github:"在 GitHub 查看源码 ↗",
    credit_img:"图片来源", credit_pd:"公有领域", credit_photo:"摄影", no_desc:"暂无详述",
    footer:"精选人类历史上的著名艺术作品 · 从史前壁画到当代艺术",
    lang_btn:"EN"
  },
  en: {
    title_sub:" Ukiyo-e Prints", subtitle:"Three centuries of Japanese woodblock prints",
    works:"prints", eras:"eras", artists:"artists",
    all_eras:"All eras", all_media:"All media", all_regions:"All regions",
    random:"Random work", all:"All",
    timeline:"Timeline", timeline_off:"Exit timeline",
    bce:"Prehistory & Antiquity", ancient:"1st–14th c.",
    m_date:"Date", m_medium:"Medium", m_location:"Location", m_country:"Country / Region",
    prev:"← Previous", next:"Next →", of_total:"",
    zoom_hint:"Scroll to zoom · double-click to enlarge · drag to pan · pinch to zoom",
    view_original:"View original", download:"Download", close:"Close",
    no_results:"No works match your filters", reset:"Reset filters",
    img_na:"No freely licensed image obtained yet", view_wiki:"View on Wikipedia",
    cr_note:"This work is still in copyright, so no freely licensed image exists. In most jurisdictions it enters the public domain in {y}.",
    cr_note_unk:"This work is still in copyright, so no freely licensed image exists.",
    fav:"Favorite", fav_on:"Favorited", fav_only:"Favorites", fav_empty:"No favorites yet — tap ♡ on any card to save it",
    by_artist:"By artist", all_artists:"All artists", artist_works:"prints",
    by_museum:"By museum", filter_artist:"Filter artists…", filter_museum:"Filter museums…",
    sort_by_count:"⇅ By count", sort_by_name:"⇅ A–Z",
    related_by:"More by this artist",
    related_era:"From the same era",
    museums:"museums",
    clear:"Clear", zoom_in:"Zoom in", zoom_out:"Zoom out", reset_zoom:"Reset", view_grid:"Toggle view", to_top:"Back to top",
    dlg_art:"Artwork details", dlg_lightbox:"High-resolution image", dlg_help:"Keyboard shortcuts",
    more_by:"View all works by this artist →", share:"Copy link", shared:"Link copied ✓",
    exhibit:"Collection", back_all:"‹ Back to all works",
    daily:"Daily pick", search_ph2:"Search title / artist / pinyin / date…",
    sort_label:"Sort", sort_default:"Default (fame)", sort_year_asc:"Date: old→new", sort_year_desc:"Date: new→old", sort_title:"By title",
    kbd:"Shortcuts", kbd_search:"Focus search", kbd_random:"Random work", kbd_artist:"Toggle artist view", kbd_timeline:"Toggle timeline", kbd_fav:"Toggle favorites", kbd_nav:"Previous / next work", kbd_close:"Close dialog / help", kbd_help:"Show this help",
    about:"About", about_title:"About this site",
    about_intro:"“1001+ Ukiyo-e Prints” is a digital gallery spanning fifty thousand years — a curated showcase of famous works of art across human history, from cave paintings to contemporary art.",
    about_sources:"Artwork metadata is gathered from Wikidata structured data (ranked by Wikipedia coverage); images come from public-domain Wikimedia Commons and are cached locally on this site.",
    about_tech:"A pure static front-end — no framework, no runtime dependencies; with bilingual UI, pinyin search and offline access (PWA), deployed on GitHub Pages.",
    about_credits:"Image rights belong to the original artists and holding institutions; a few 20th-century works under copyright are shown as placeholders with a link to Wikipedia.",
    about_works:"prints", about_artists:"artists", about_images:"local HD images",
    about_github:"View source on GitHub ↗",
    credit_img:"Image source", credit_pd:"Public domain", credit_photo:"Photo", no_desc:"No description yet",
    footer:"A curated selection of famous works of art · from cave paintings to contemporary art",
    lang_btn:"中文"
  }
}
};
